### ISSUE TITLE
error when run pan.py -d -t

### ISSUE THREAD

**Issue by hobiron21** [008karan/PAN_OCR#2]
after run i get :

[+] Initializing Darknet
[/] Init Classifier failed, exiting now

**Comment by eliyaz-virtech** [comment]
same issue for me!

**Comment by 008karan** [comment]
Looks like yolo could not find required files.

**Comment by aman-ar** [comment]
Same issue. Any solution for this?

**Comment by dedetuga** [comment]
There is no weight for darknet work with, this is the problem!!! 
where can i find the weight files ???

**Comment by 008karan** [comment]
here is link to download darknet-53 weights. [ http://pjreddie.com/media/files/darknet53.conv.74](url)

**Comment by anandhkirupa** [comment]
where to keep this darknet-53 weights file @008karan
