### ISSUE TITLE
Misclassification of Character

### ISSUE THREAD

**Issue by shanku007** [008karan/PAN_OCR#4]
Hey, I am trying to make a pan OCR. I tried running your project but the tesseract seems to misclassify some characters like classifying 9 as 0, 5 as S and so on. Also, I am not running the OCR for the whole pan card but first localizing the name and other details and then running OCR for that part of the image with configuration --oem 3 and --psm 13.
Would you please help me in any way whatsoever.
Also could you please advise me if it's better to run OCR on a localised part of the image or performing OCR on whole pan card

**Comment by 008karan** [comment]
That's the limitation of the tesseract. You can apply some filters on the localized image to enhance it so that tesseract can read it there are many of them. also, change the tesseract modes to find which is more suitable. Otherwise, use Google or Microsoft API to read images.
