### ISSUE TITLE
what is left_x while classifying the image.

### ISSUE THREAD

**Issue by sbind29893** [008karan/PAN_OCR#5]
i have trained yolov3 weights using 5 classes which is (pancard,name,fathername,date,pan number). When i am trying to run it is giving me no label found message

**Comment by sbind29893** [comment]
ValueError: invalid literal for int() with base 10: '(left_x:'

this is the error im getting

**Comment by sbind29893** [comment]
i resolved this...i just wanted to know where you have defined this left_x key...

**Comment by 008karan** [comment]
it is in utils/locate_asset.py.

**Comment by sbind29893** [comment]
Earlier when i was using darknet without your repository..it was showing only coordinates value..without the key such as left_x...i want to know have you done any config changes in darknet.

**Comment by sbind29893** [comment]
And one more thing the detection is taking upto 35 seconds...im using ur exe file

**Comment by 008karan** [comment]
not config changes. I wanted to ignore some labels like photos etc. thats why it is used

**Comment by sbind29893** [comment]
can you please share your darknet repo.

**Comment by 008karan** [comment]
all changes are uploaded here

**Comment by sbind29893** [comment]
Why it is taking upto 40 seconds to detect one image..can you tell me your average detection time ?

**Comment by 008karan** [comment]
it is the inference time of the model. and depends on the system also. Take the system with more RAM if you want to reduce it.

**Comment by sbind29893** [comment]
I am using MSI nvidia GTX1070 with 16GB ram.

**Comment by sbind29893** [comment]
Anyways it is detecting the pan card properly and converting it into csv data...thank you soo much for this repo.
