### ISSUE TITLE
Could you please share your weight files?

### ISSUE THREAD

**Issue by vfbsilva** [008karan/PAN_OCR#7]
I've stumbled upon your article while doing some research. I really liked your approach and would like to test it to get some numbers on the performance of the detection in devices like the jetson x2 and nano/ But I'm in a bit overwhelmed of things to do. Could you maybe kindly provide either your mark ups or the weights files itself so I could run some numbers here?

**Comment by 008karan** [comment]
Have shared it. You can find link in readme
